export const GET_HOUSE_LOADING_IN_PROGRESS = 'GET_HOUSE_LOADING_IN_PROGRESS';
export const GET_HOUSE_SUCCESS = 'GET_HOUSE_SUCCESS';
export const GET_HOUSE_ERROR = 'GET_HOUSE_ERROR';

export const HREF_HOUSECONTROLLER_GET_SINGLE = '/api/house/get?id=';