export const GET_APARTMENTS_SUCCESS = 'GET_APARTMENTS_SUCCESS';
export const GET_APARTMENTS_ERROR = 'GET_APARTMENTS_ERROR';
export const GET_APARTMENTS_LOADING_IN_PROGRESS = 'GET_APARTMENTS_LOADING_IN_PROGRESS';

export const HREF_APARTMENTCONTROLLER_GET_SINGLE = '/api/apartment/getall';